# SPDX-License-Identifier: GPL-3.0-only
param([string]$Compiler = '', [switch]$SkipTests)
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot 'version.ps1')
$projectVersion = Read-MorseBridgeVersion -ProjectRoot $projectRoot
if (-not $Compiler) { $Compiler = Join-Path $projectRoot '.tools/w64devkit/bin/g++.exe' }
if (-not (Test-Path -LiteralPath $Compiler)) {
    $found = Get-Command g++.exe -ErrorAction SilentlyContinue
    if ($found) { $Compiler = $found.Source } else { throw 'Compiler fehlt. Zuerst scripts/get-tools.ps1 ausfuehren.' }
}
$compilerDirectory = Split-Path -Parent $Compiler
$windres = Join-Path $compilerDirectory 'windres.exe'
$output = Join-Path $projectRoot 'dist'
$build = Join-Path $projectRoot 'build'
New-Item -ItemType Directory -Force -Path $output,$build | Out-Null
$buildUtc = [DateTime]::UtcNow.ToString("yyyy-MM-dd'T'HH:mm:ss'Z'", [Globalization.CultureInfo]::InvariantCulture)
$buildInfo = "// Generated by scripts/build.ps1; do not edit.`n#pragma once`n#define MB_BUILD_UTC_STRING `"$buildUtc`"`n#define MB_BUILD_UTC_WSTRING L`"$buildUtc`"`n"
[IO.File]::WriteAllText((Join-Path $build 'build_info.hpp'), $buildInfo, [Text.UTF8Encoding]::new($false))
$manifest = [IO.File]::ReadAllText((Join-Path $projectRoot 'windows/app.manifest.in')).Replace('@VERSION@', $projectVersion.WindowsVersion)
[IO.File]::WriteAllText((Join-Path $build 'app.manifest'), $manifest, [Text.UTF8Encoding]::new($false))
Push-Location $projectRoot
try {
    & $windres '-Ibuild' '-Iwindows' 'windows/app.rc' '-O' 'coff' '-o' 'build/app.res'
    if ($LASTEXITCODE -ne 0) { throw 'Resource compilation failed' }
    $flags = @('-std=c++17','-O2','-Wall','-Wextra','-Wpedantic','-Werror','-DUNICODE','-D_UNICODE','-D_WIN32_WINNT=0x0A00','-static','-static-libgcc','-static-libstdc++')
    & $Compiler @flags '-DMB_GENERATED_BUILD_INFO' '-mwindows' '-municode' 'windows/main.cpp' 'build/app.res' '-o' 'dist/MorseBridge.exe' '-lsetupapi' '-lcomctl32' '-lgdi32' '-luser32' '-ladvapi32' '-lwtsapi32' '-lshell32' '-luuid' '-lgdiplus' '-lole32' '-lavrt' '-lwinhttp' '-ldwmapi' '-luxtheme'
    if ($LASTEXITCODE -ne 0) { throw 'C++ compilation failed' }
    if (-not $SkipTests) {
        & $Compiler @flags 'tests/core_tests.cpp' '-o' 'build/core_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Test compilation failed' }
        & './build/core_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Core tests failed' }
        & $Compiler @flags 'tests/tone_tests.cpp' '-o' 'build/tone_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Tone test compilation failed' }
        & './build/tone_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Tone tests failed' }
        & $Compiler @flags 'tests/audio_core_tests.cpp' '-o' 'build/audio_core_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Audio format test compilation failed' }
        & './build/audio_core_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Audio format tests failed' }
        & $Compiler @flags 'tests/audio_output_tests.cpp' '-o' 'build/audio_output_tests.exe' '-lole32' '-luuid' '-lavrt'
        if ($LASTEXITCODE -ne 0) { throw 'Audio thread test compilation failed' }
        & './build/audio_output_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Audio thread tests failed' }
        & $Compiler @flags '-Itests/arduino_stub' 'tests/firmware_tests.cpp' '-o' 'build/firmware_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Firmware test compilation failed' }
        & './build/firmware_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Firmware tests failed' }
        & $Compiler @flags 'tests/update_tests.cpp' '-o' 'build/update_tests.exe' '-lwinhttp'
        if ($LASTEXITCODE -ne 0) { throw 'Update test compilation failed' }
        & './build/update_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Update tests failed' }
        & $Compiler @flags 'tests/settings_tests.cpp' '-o' 'build/settings_tests.exe' '-lshell32' '-lole32' '-luuid' '-ladvapi32'
        if ($LASTEXITCODE -ne 0) { throw 'Settings test compilation failed' }
        & './build/settings_tests.exe'
        if ($LASTEXITCODE -ne 0) { throw 'Settings tests failed' }
    }
    Get-Item -LiteralPath (Join-Path $output 'MorseBridge.exe') | Select-Object FullName,Length,LastWriteTime
} finally { Pop-Location }
